#!/bin/sh -e

# create the log directory if it doesn't exist
[ -d /var/log/gonano/ssh ] || mkdir -p /var/log/gonano/ssh %>

# tell svlogd to drop the stdout into our custom location
cd /var/log/gonano/ssh
exec svlogd -v -ttt /var/log/gonano/ssh
