#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# create the runit definitions for logvac
directory '/etc/service/logvac' do
  recursive true
end

directory '/etc/service/logvac/log' do
  recursive true
end

hook_file '/etc/service/logvac/log/run' do
  source 'runit/logvac-log'
  mode 0755
end

hook_file '/etc/service/logvac/run' do
  source 'runit/logvac'
  mode 0755
end

service 'logvac' do
  action :enable
end
