#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Stop logvac
service 'logvac' do
  action :disable
end

# Remove logvac runit definition
directory '/etc/service/logvac' do
  action :delete
end

# Stop narc
service 'narc' do
  action :disable
end

# Remove narc runit definition
directory '/etc/service/narc' do
  action :delete
end
