#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

logger = Nanobox::Logvac.new(host: payload[:logvac_host], id: "#{payload[:component][:uid]}.#{payload[:member][:uid]}[update]")

local_logvac_md5 = execute "local logvac md5" do
  command "cat /var/nanobox/logvac.md5"
  not_if { ! ::File.exists? "/var/nanobox/logvac.md5" }
end

aws_logvac_md5 = execute "aws logvac md5" do
  command <<-END 
    bash -c 'curl \
      -f \
      -k \
      https://d3ep67zochz54j.cloudfront.net/logvac/linux/amd64/logvac.md5 \
        | tee /var/nanobox/logvac.md5'
  END
end

if local_logvac_md5 != aws_logvac_md5
  logger.puts('Logvac is out of date, updating to latest')

  # Stop logvac
  service 'logvac' do
    action :disable
    not_if { !Dir.exist?('/etc/service/logvac') }
  end

  execute "Download logvac" do
    command <<-END 
      bash -c 'curl \
        -f \
        -k \
        -o /usr/local/bin/logvac
        https://d3ep67zochz54j.cloudfront.net/logvac/linux/amd64/logvac'
    END
  end

  execute "Chmod logvac" do
    command <<-END 
      bash -c 'chmod 755 /usr/local/bin/logvac'
    END
  end

  service 'logvac' do
    action :enable
    not_if { !Dir.exist?('/etc/service/logvac') }
  end
else
  logger.puts('Logvac is up to date.')
end

local_hooks_md5 = execute "local hooks md5" do
  command "cat /var/nanobox/hooks.md5"
  not_if { ! ::File.exists? "/var/nanobox/hooks.md5" }
end

aws_hooks_md5 = execute "aws hooks md5" do
  command <<-END
    bash -c 'curl \
      -f \
      -k \
      https://d1ormdui8qdvue.cloudfront.net/hooks/logvac-stable.md5 \
        | tee /var/nanobox/hooks.md5'
  END
end

if local_hooks_md5 != aws_hooks_md5
  logger.puts "Hooks are out of date, updating to latest"
  execute "update hooks" do
    command <<-END
      bash -c 'curl \
          -f \
          -k \
          https://d1ormdui8qdvue.cloudfront.net/hooks/logvac-stable.tgz \
            | tar -xz -C /opt/nanobox/hooks'
    END
  end
else
  logger.puts "Hooks are up to date."
end