#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

local_logvac_md5 = execute "local logvac md5" do
  command "cat /var/nanobox/logvac.md5"
  not_if { ! ::File.exists? "/var/nanobox/logvac.md5" }
end

aws_logvac_md5 = execute "aws logvac md5" do
  command "curl \
    -f \
    -k \
    https://d3ep67zochz54j.cloudfront.net/logvac/linux/amd64/logvac.md5 \
      | tee /tmp/logvac.md5"
end

if local_logvac_md5 != aws_logvac_md5
  # Stop logvac
  service 'logvac' do
    action :disable
    not_if { !Dir.exist?('/etc/service/logvac') }
  end

  execute "Download logvac" do
    command "curl \
      -f \
      -k \
      -o /usr/local/bin/logvac \
      https://d3ep67zochz54j.cloudfront.net/logvac/linux/amd64/logvac"
  end

  execute "Chmod logvac" do
    command "chmod 755 /usr/local/bin/logvac"
  end

  service 'logvac' do
    action :enable
    not_if { !Dir.exist?('/etc/service/logvac') }
  end

  execute "Finalize update" do
    command "mv /tmp/logvac.md5 /var/nanobox/logvac.md5"
  end
end

local_hooks_md5 = execute "local hooks md5" do
  command "cat /var/nanobox/hooks.md5"
  not_if { ! ::File.exists? "/var/nanobox/hooks.md5" }
end

aws_hooks_md5 = execute "aws hooks md5" do
  command "curl \
    -f \
    -k \
    https://d1ormdui8qdvue.cloudfront.net/hooks/logvac-stable.md5 \
      | tee /tmp/hooks.md5"
end

if local_hooks_md5 != aws_hooks_md5
  execute "update hooks" do
    command "curl \
      -f \
      -k \
      https://d1ormdui8qdvue.cloudfront.net/hooks/logvac-stable.tgz \
        | tar -xz -C /opt/nanobox/hooks"
  end

  execute "Finalize update" do
    command "mv /tmp/hooks.md5 /var/nanobox/hooks.md5"
  end
end
